### ISSUE TITLE
Get rid of sleep(0.5ms) in X11 event loop

### ISSUE THREAD

**Issue by tonsky** [HumbleUI/JWM#129]
https://github.com/JetBrains/JWM/blob/c6762d5c61a8cb06dae5023ca43ddd43b87698cf/linux/cc/WindowManagerX11.cc#L195

Problem:

- Can’t use blocking event loop because no way to schedule runOnUIThread from another threads
- Non-blocking event loop eats lots of CPU

Ideas:

- don’t sleep at all
- provide user-defined lambda to call instead of sleeping

**Comment by dzaima** [comment]
I have a `poll`-based event loop [here](https://github.com/dzaima/JWM/commit/d534b9d912f23f15ef1209f576d6f9229795e9ab) that brings background CPU usage down to a nice 0%, and works on whatever I've thrown at it; if that seems like a good way to go forward, I can PR that.

**Comment by tonsky** [comment]
I will need some time to restore the context back, will take a look. @Alex2772 what do you think?

**Comment by Alex2772** [comment]
IMHO the solution is quite elegant except it's hard to understand [the magic of the buffer size](https://github.com/dzaima/JWM/compare/main...dzaima:patch-2#diff-ffa5df56b1c0139498100749b63c2c8773297f36b51e6ba7fcc3e19a04a3da8fR214).

PR is welcome!

**Comment by dzaima** [comment]
The pipe should only ever have a maximum of 2 characters in it, so a buffer size of two should be technically fine. Nevertheless I made it somewhat bigger just in case (don't want to use too much stack though); I'll add some comments & PR tomorrow
