### ISSUE TITLE
Windows: getScreens report incorrect screen configuration

### ISSUE THREAD

**Issue by tonsky** [HumbleUI/JWM#141]
Expected:

<img width="368" alt="Screenshot 2021-08-27 at 00 39 04" src="https://user-images.githubusercontent.com/285292/131045098-49961fcb-938d-4e4f-97a8-f1640c5b537c.png">

Actual:

<img width="384" alt="Screenshot 2021-08-27 at 00 38 38" src="https://user-images.githubusercontent.com/285292/131045072-b548f47b-001d-46b2-a27f-9c6768a8752c.png">

**Comment by ItoYo16u** [comment]
Does this happen only when using multiple screens?

**Comment by tonsky** [comment]
Yes
