### ISSUE TITLE
X11: Window::getContentRect spills outside of getWindowRect

### ISSUE THREAD

**Issue by tonsky** [HumbleUI/JWM#144]
![Screenshot from 2021-08-28 16-54-47 (1)](https://user-images.githubusercontent.com/285292/131222258-f6c1322c-1f68-4da2-bd1f-66c588806a00.png)

**Comment by dzaima** [comment]
at least on Linux Mint Cinnamon, the top-left corner can even go negative - `XGetWindowAttributes` doesn't give the actual decoration size. `_NET_FRAME_EXTENTS` seems to give proper ones though, will look into it
