### ISSUE TITLE
Possible to attach to existing OS-specific window handle given to the process (not spawn new window + handle)? 

### ISSUE THREAD

**Issue by GavinRay97** [HumbleUI/JWM#150]
Hello, first I'd like to thank the contributors of this library -- it opens up very exciting possibilities and is sorely needed in the ecosystem. So thank you all 😃 

---

**My question:**

I've been browsing the source, trying to understand if the following scenario is possible:
1. A process is created (let's call it `ParentApp`) and launches it's own window/UI
2. `ParentApp` creates a new window + handle, let's call this `ChildWindowHandle`, and passes it to our `JWM` program
3. We would like to receive this `ChildWindowHandle` pointer and use it to render/attach our `JWM` app UI to
	- On Windows this would be an `HWND`
	- On Linux, this would be an `XWindowID`
	- On Mac OSx, this would be an `NSView` or `HIView`

If this sounds strange to you/you can't imagine why you would want to do this:

- One usecase is plugin-based UI's where developers don't control the host program and publish plugins as shared libs (`.dll`/`.so`/`.dylib`)
	- These plugins get loaded by the parent application and are "handed" a pre-made `ChildWindowHandle` to render into

A popular example (my usecase): **VST Audio Plugins for DAW's**
- https://en.wikipedia.org/wiki/Virtual_Studio_Technology

It would be amazing to be able to author audio plugins (or at least the UI's) in say, Kotlin. General availability to JVM languages would be revolutionary.

For a code short example, essentially what I'm asking is if something like this is possible (minus the low-level X11 stuff, just the bit about receiving and using the `parentWindowHandle` to render):
```kt
import kotlinx.cinterop.*
import Xlib.*

fun vstOnAttached(parentWindowHandle: COpaquePointer, platform: String) {
    val msg = "Hello, World!"
    
    val d = XOpenDisplay(null)
    if (d == null) {
        println("Cannot open display")
        return
    }
 
    val s = XDefaultScreen(d)

  /* Window XCreateSimpleWindow(display, parent, x, y, width, height, border_width, 
                                border, background) */
    val w = XCreateSimpleWindow(d, parentWindowHandle.reinterpret<Window>, 10, 10, 160, 160, 1,
                                XBlackPixel(d, s), XWhitePixel(d, s))
    XSelectInput(d, w, ExposureMask or KeyPressMask)
    XMapWindow(d, w)
    val e = nativeHeap.alloc<XEvent>()
 
    while (true) {
        XNextEvent(d, e.ptr)
        if (e.type == Expose) {
            XFillRectangle(d, w, XDefaultGC(d, s), 55, 40, 50, 50)
            XDrawString(d, w, XDefaultGC(d, s), 45, 120, msg, msg.length)
        }
        else if (e.type == KeyPress) break
    }
 
    XCloseDisplay(d)
    nativeHeap.free(e)
}
```

Curious if there's any way to accomplish this currently?
Thank you

---

### Boring Contextual Details Below

The way audio plugins work, is that the host application (generally a DAW) allocates a window handle and gives the plugin the window to render into:

![image](https://user-images.githubusercontent.com/26604994/132109627-c8dd3163-5a38-4ac0-b241-d0517e533632.png)

- https://steinbergmedia.github.io/vst3_doc/base/classSteinberg_1_1IPlugView.html#a9fbc345c1e87f7e6210a8a49fdb96793
	- ![image](https://user-images.githubusercontent.com/26604994/132109671-8833b607-20bb-44e4-88f4-837e4d55fad4.png)

- https://steinbergmedia.github.io/vst3_doc/base/group__platformUIType.html
	- ![image](https://user-images.githubusercontent.com/26604994/132109681-55a9a358-3887-48e1-a797-cd5351abf71f.png)

**Comment by tonsky** [comment]
Sounds like a great use case. Do you think it should support drawing only or window events too? E.g. mouse move or window resize?

**Comment by GavinRay97** [comment]
> Sounds like a great use case. Do you think it should support drawing only or window events too? E.g. mouse move or window resize?

IMO the ability to respond to those would be really useful -- particularly the mouse movement (a lot of FX use cursor-movement based UI updates), but I'd be grateful for whatever is possible.

Many audio plugins don't handle resizing 😅 

Here's a video example of "Responds to mouse movement in UI, but you're SOL if you want to resize the thing" 

- (Most plugin UI's don't use vector-based graphics, and instead ship percentage-based scaled UIs. So you can select 100%, 120%, 150%, whatnot and it loads the image assets in actual different dimensions. Only recently have some plugins started to shift towards fully-scalable UI's)


https://user-images.githubusercontent.com/26604994/132262119-b44c3537-81aa-4854-a420-22afcd77b24a.mp4

**Comment by GavinRay97** [comment]
Though I should prolly clarify -- I don't intend to create a JVM in native code (C/C++/Rust etc) and call it this way.

If this functionality is added, I would try to work on getting GraalVM to compile JWM so that it's useable with native binaries and shared-libs, or Kotlin Native (if that's an option).

And I would use either Graal's `@CFunction` or Kotlin Native's equivalent, to create the underlying native window pointer

**Comment by tonsky** [comment]
Interesting! I see some obstacles on your plan:

- Compiling to GraalVM might get tricky
- Window events would not probably work as nice when using only part of the window (we didn’t planned for this)
- JWM was designed to control rendering itself (buffer swaps, vsync, see Layer interface). It might get in the way if your host app is doing it for you
- Calling Java from native is probably possible, but adds extra work

May I ask, what kind of features do you plan to get access to by using JWM instead of native Win32 APIs? Especially if you are planning to write the rest of your plugin in native code (if I understand you correctly)?

Re: Java Window ctor, it takes a pointer to our own native C++ Window class, e.g. WindowWin32

**Comment by GavinRay97** [comment]
> Re: Java Window ctor, it takes a pointer to our own native C++ Window class, e.g. WindowWin32

Ahh, well it would not be so simple then! Nothing ever is, aye? 😅 

> May I ask, what kind of features do you plan to get access to by using JWM instead of native Win32 APIs? Especially if you are planning to write the rest of your plugin in native code (if I understand you correctly)?

I want to open up audio plugin development to the JVM, as a platform.

Personally I am not a fan of C++, and I can imagine how nice it would be to be able to write plugins in a "nicer" (sorry) language like Kotlin or Java.

There's no getting around the fact that you need native code to do this -- but that native code doesn't ACTUALLY have to be C/C++.

What I mean by that is, for example there's someone who has ported the VST C++ API's to a C FFI wrapper and then done Kotlin Native on top of that.

- https://github.com/Durun/vst3kotlin
- https://github.com/Durun/vst3kotlin/blob/f1082278b6c763fbebb4318c83f7aecdf501e233/vst3pluginterface/src/nativeMain/kotlin/durun/vst3kotlin/pluginterface/vst/editController.kt

Here's a Kotlin Native binding to the `EditController` C++ class of the VST SDK:
- https://steinbergmedia.github.io/vst3_doc/vstsdk/classSteinberg_1_1Vst_1_1EditController.html
```kt
class EditController(
	override val ptr: CPointer<IEditController>
) : PluginBase() {
	private val log by logger()
	private val this2: VstInterface<CPointer<IEditController2>> = queryVstInterface(IEditController2_iid)
	private val thisPtr2: CPointer<IEditController2> get() = this2.ptr.reinterpret()
```

So my intention was to:
- Use either:
	- The existing Kotlin Native SDK (which I contacted and got permission from the author to do)
	- Use GraalVM's `@CFunction` to write bindings in Java to the native code, making it consumable from Java
		- See below for an example of binding + calling OpenGL's C API to Java without touching JNI/native code
		- https://www.praj.in/posts/2020/opengl-demo-using-graalvm/
- Use JWM's Windowing API to fill in the only missing piece on the JVM platform -- the actual rendering and management of the window
- Use GraalVM or Kotlin Native to compile the result to a shared lib `.dll`/`.so`/`.dylib`
- The end result is being able to consume the C++ VST3 SDK and interact with bindings done entirely from Java/Kotlin, and publishing native artifacts 🤯 
- No more C++ for audio dev!
- Everyone sheds a tear in joy 🥲, slow claps 👏 and goes home 👪

---

> Compiling to GraalVM might get tricky

Yeah definitely -- I see there are issues with it currently and have checked out your notes and build scripts.

I have some familiarity with it, and had planned to troubleshoot getting it working + reach out to the Graal devs on Slack for ideas (I've done this a good number of times and they're really helpful) if I absolutely couldn't make headway on it.

It's possible that:
- I cannot get it working any better
- None of the Graal devs have any clue, or can be bothered to spend time trying to answer my questions

Which would suck, but that's a "cross that bridge when I get to it -- with a positive attitude" sort of thing haha.

> Window events would not probably work as nice when using only part of the window (we didn’t planned for this)

Just to double check, could you elaborate more on this?

I don't actually know very much about windowing API's, does this mean that child windows are more like partial windows rather than regular whole windows?


> JWM was designed to control rendering itself (buffer swaps, vsync, see Layer interface). It might get in the way if your host app is doing it for you

I think the host app essentially hands a "blank canvas" window, where you're free to do to the window what you wish. Someone had asked about using `VSTGUI` (A UI framework for VST plugins) with OpenGL custom rendering, and the VST devs answered: "Just give VST the `HWND` and then have your OpenGL app do the rendering on the window":

![image](https://user-images.githubusercontent.com/26604994/132611364-300eabc6-2b96-46a2-b5f1-d2db538c3dbc.png)

**Comment by GavinRay97** [comment]
After speaking with some folks who are more experienced at Win32 dev, it seems the expected design pattern is to simply re-parent windows.

So if you are given a `HWND` to attach to, it's expected you do this by calling `SetParent(parentHwnd, thisHwnd);`


> _"Yes, you can reparent literally any window in the system to yourself."_
> _"If you're given an HWND, reparenting is basically the expected usage pattern, as you can't do much with that HWND except reparenting to it."_

So maybe something roughly like this is an easier implementation?

```java
interface Reparentable {
   public void reparentWindowTo(long parentPlatformSpecificWindowHandle);
}

abstract class Window implements Reparentable {
  private long platformSpecificWindowHandle; // HWND, XWindowID, NSView, etc
}

class Win32Window extends Window {
  // https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setparent
  private native SetParent(long hWndChild, long hWndNewParent);

  @Override
  public void reparentWindowTo(long parentPlatformSpecificWindowHandle) {
    this.SetParent(this.platformSpecificWindowHandle, parentPlatformSpecificWindowHandle);
  }
}
```

And then trying to get JWM built as a native resource with Graal or Kotlin Native should be the only barrier left if re-parenting is also available (and an acceptable design pattern) on other platforms I think?

**Comment by tonsky** [comment]
>> Window events would not probably work as nice when using only part of the window (we didn’t planned for this)

> Just to double check, could you elaborate more on this? I don't actually know very much about windowing API's, does this mean that child windows are more like partial windows rather than regular whole windows?

Me neither :)

> The host app essentially hands a "blank canvas" window, where you're free to do to the window what you wish

Just to reiterate: host app creates an empty window for you, and your plugin is running in a different process? And from that process you want to reparent the original window to yourself? So we need something like `Window::makeFromHWND(long hwnd)` that would do reparenting internally. Does that sounds like what you need?

**Comment by GavinRay97** [comment]
> host app creates an empty window for you, and your plugin is running in a different process?

Yeah, correct. The architecture of the audio plugin is:

```
Digital Audio Workstation process
          |                                
  VST3 Interfaces (C++) 
          |                         
      MyPlugin.dll
```  

The DAW host process will allocate an OS-specific empty window, and then call:
`IPlugView::attached(void* windowHandle, enum kPlatformName)`

And then the plugin is responsible for taking the window handle and figuring out how to draw itself on that window.

Which I guess apparently means:
`"Set this window as your app's parent/container window and then spawn your own window as it's child."`

On Windows that's `HWND` and `SetParent()` and on Linux, I believe that's an XID (`"Window"`) and `XReparentWindow()`:
```c
XReparentWindow(display, w, parent, x, y)
      Display *display;
      Window w;
      Window parent;
      int x, y;
```

![image](https://user-images.githubusercontent.com/26604994/134791068-dc893808-a237-447a-8c7e-aa09d2d96bae.png)

> And from that process you want to reparent the original window to yourself? So we need something like `Window::makeFromHWND(long hwnd)` that would do reparenting internally. Does that sounds like what you need?

Yeah that sounds fantastic 💯

**Comment by tonsky** [comment]
Ok, I think it’s getting more clearer now. Before, I though that SetParent() has something to with process separation. Now I see they are all in the same process, and SetParent actually requires two windows: parent and child. So it’s a way to put one window inside another.

In light of that, I think the original proposal of `Window::setParent(long hwnd)` would serve this purpose better. I am not sure how would one window inside another look or work, but we can start with this method only and you can report what else do you need.

**Comment by tonsky** [comment]
See https://github.com/HumbleUI/JWM/commit/8417f29175c11568a5ec8531e0336bcb0a4f43f9, let me know if it works

**Comment by GavinRay97** [comment]
Awesome -- thank you!

Going to build this and then try to make a dummy Win32 app that spawns one Window, and then fires up JVM and sends across the `HWND` to a Java class method that calls this new function 👍

**Comment by GavinRay97** [comment]
@tonsky It works! Thanks a ton!! ❤️ 

Check it out: how neat is this? 🙌 

https://user-images.githubusercontent.com/26604994/134979997-018af42c-d6b5-49d5-9cbb-2f90d7500ac1.mp4
