### ISSUE TITLE
LayerWGL.cc:103 Failed to create rendering context

### ISSUE THREAD

**Issue by Hilal-Anwar** [HumbleUI/JWM#152]
I was to trying to run https://github.com/HumbleUI/JWM/blob/main/docs/GettingStarted.java but got an error like this

LayerWGL.cc:103 Failed to create rendering context
Exception in thread "main" org.jetbrains.jwm.LayerNotSupportedException: Failed to create rendering context
	at org.jetbrains.jwm.LayerGL._nAttach(Native Method)
	at org.jetbrains.jwm.LayerGL.attach(LayerGL.java:19)
	at EventHandler.<init>(GettingStarted.java:22)
	at GettingStarted.main(GettingStarted.java:8)

I am using jdk 16.
I tried it using jdk 11 but got the  same error.
I even tried using  a version like 0.1.274 , but got a similar error.

Can anyone explain this.

**Comment by tonsky** [comment]
What’s your hardware configuration? Graphics card model? You are on Windows, right? Which version?

**Comment by Hilal-Anwar** [comment]
Thanks Nikita for your reply , you are really a humble guy.

My computer  hardware  configuration

Device name	ABC-PC
Processor	Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz   2.10 GHz
Installed RAM	4.00 GB
Device ID	66AD9AE2-BBB3-4203-8BA7-2BADA96B35F6
Product ID	00330-80000-00000-AA941
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

OS 

Edition	Windows 10 Pro
Version	21H1
Installed on	‎18-‎Jun-‎20
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

I have no dedicated graphics card , only the integrated one Intel(R) HD Graphics 5500

**Comment by tonsky** [comment]
Okay, one of the reasons might be that you don’t have OpenGL drivers in the system. Another one that Intel HD 5500 has some problems with it.

Can you try LayerD3D12 instead of LayerGL? It’s supposed to work better on Windows

**Comment by Hilal-Anwar** [comment]
Yes it is working .
I replaced  LayerD3D12 with LayerGL and got a blank window

Thanks for your help bro.

By the way when will this library be completed. I mean , I am just curious
