### ISSUE TITLE
Progress bar API

### ISSUE THREAD

**Issue by mworzala** [HumbleUI/JWM#191]
See https://www.electronjs.org/docs/latest/tutorial/progress-bar

I see two options for an API here.
1. Electrons route, a `Window` method to set the current progress. The problem here is that Windows is the only platform capable of a progress bar per window.
2. An `App` method to set the progress for the entire app, with an overload to provide the window (or a secondary method on window to set it per window).

Either way it is confusing on some platforms.

**Comment by tonsky** [comment]
I like the Electron route. If one platform requires Window, we might as well make other platforms think the same way, even if it will make no difference for them.

**Comment by mworzala** [comment]
Makes sense, what is the standard for attribution in this repo? After looking at Electrons way of doing this I cannot imagine a scenario where the implementation does not look nearly identical to theirs.

**Comment by tonsky** [comment]
Electron is MIT:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

I don’t think our use will count as “substantial use”, but you can always leave a link pointing to their source next to impl
