### ISSUE TITLE
X11: Maximize and then restore does not fire eventwindowmove, confusing getWindowRect

### ISSUE THREAD

**Issue by tonsky** [HumbleUI/JWM#198]
Steps to reproduce:

1. Maximize window
2. Restore 

![Screenshot from 2022-02-07 17-30-51](https://user-images.githubusercontent.com/285292/152831017-d01db0d5-668d-43eb-8d38-5dc85d2fc838.png)

**Comment by dzaima** [comment]
Also just resizing the window without moving seems to break it. Seems `ConfigureNotify` isn't a reliable way to get window location.

**Comment by dzaima** [comment]
Seems that within `ConfigureNotify` the resizing hasn't been completed, so even retrieving the proper position with `getWindowRect` will return the position before the resize.. Not sure what to do about that.
