### ISSUE TITLE
macOS: Work around for -XstartOnMainThread

### ISSUE THREAD

**Issue by mworzala** [HumbleUI/JWM#210]
JavaFX appears to use [`performSelectorOnMainThread`](https://developer.apple.com/documentation/objectivec/nsobject/1414900-performselectoronmainthread) to start the app, perhaps it is worth doing something similar. Should also be easier to work with native image, as apparently the option [does not work](https://github.com/oracle/graal/issues/1861) (though I have not tested personally)

Eg 
```java
App.init(() -> {
    Window window = App.makeWindow();
    // ...

    App.start();
});
```

**Comment by mworzala** [comment]
> but as far as I remember it didn’t worked without `-XstartOnFirstThread` for some reason anyway

As far as I could tell at a glance, this requires `[NSApp run]` to have been called for the inner part to be executed.

I do seem to have a version working locally without `-XstartOnFirstThread`, although the API will need to change. There needs to be some runnable to do user init. It could be what I posted above, but I am not sure there is any reason to separate `App#init` and `App#start`, eg something like
```java
App.init(() -> {
    Window window = App.makeWindow();

    // ...
}); // blocks for app runtime
```

Let me know what you think regarding API while I clean up my local version.

**Comment by tonsky** [comment]
The design you proposed is nice. So `init` will do what now `init` + `start` do combined, right? And `init` will block, in the hope you could do rest of your logic inside event handlers, right?
