### ISSUE TITLE
delombok'ed sources give incorrect line pointers in error messages

### ISSUE THREAD

**Issue by dzaima** [HumbleUI/JWM#211]
Delombok changes the number of lines in the sources, thus leading to stacktraces with line numbers (coming from non-delomboked compilations of JWM) being off, making debugging a lot more confusing.

**Comment by mworzala** [comment]
What is the reason for Lombok in this case? It doesn't seem like a ton of typing to add the getters and they don't change super often. 

Also would save a step building which is nice.

**Comment by dzaima** [comment]
> Hmm, you might be right. What do you think the solution should be? Ship `-sources.jar` as-is, without delomboking?

I don't see much benefit for delombok in the sources. The problems I see are readability (which delombok does not make better imo), and the IDE viewing it not liking unknown libraries (but it already does that due to there still being calls to lombok, among also jetbrains annotations). Or are there some other uses for `-sources.jar`?

Alternatively, compilation could work on the delombok sources, but I assume that'd be hard to make work with the custom build process, and would complicate development while working on the regular non-delombok sources.
