### ISSUE TITLE
X11: Scrolling in another window affects scroll distance in JWM's

### ISSUE THREAD

**Issue by dzaima** [HumbleUI/JWM#214]
1. scroll a lot in an unrelated window
2. hover over a JWM window
3. scroll once
4. observe scroll delta being very big due to adding up the scrolling done in the other window

(for the longest time I was thinking my scroll wheel was just broken :|)

**Comment by tonsky** [comment]
Lol, thanks for reporting :)

**Comment by dzaima** [comment]
So far, my understanding is that this is just.... intentional behavior? [here's](https://github.com/GNOME/gtk/blob/d45281e6c740591d228762c6b0dce03bf6e09791/gdk/x11/gdkdevice-xi2.c#L759-L770) GTK's scroll wheel logic if i'm reading correctly, and [here](https://github.com/GNOME/gtk/blob/d45281e6c740591d228762c6b0dce03bf6e09791/gdk/x11/gdkdevice-xi2.c#L779-L791) is a function to unset the current value, invoked at least [here](https://github.com/GNOME/gtk/blob/d45281e6c740591d228762c6b0dce03bf6e09791/gdk/x11/gdkdevicemanager-xi2.c#L2059-L2064). This results in the first scroll event after regaining focus being used as "calibration", thus making said event not actually scroll. cmon X11/XI :/
