### ISSUE TITLE
X11: When scrolling horizontally, primary mouse button events are constantly generated

### ISSUE THREAD

**Issue by tonsky** [HumbleUI/JWM#217]
![Screenshot from 2022-02-16 22-35-04](https://user-images.githubusercontent.com/285292/154363981-43937706-8447-4aa3-b92c-46547574f727.png)

Logitech MX Master 3 + side wheel + Ubuntu 20.04

**Comment by dzaima** [comment]
I think
https://github.com/HumbleUI/JWM/blob/a0cb3b06261c939f82cb07bad56ba411ed986f99/linux/cc/MouseButtonX11.cc#L15-L17
should be extended to `v<4 || v>7` - see [this](http://who-t.blogspot.com/2009/06/button-mapping-in-x.html)
