### ISSUE TITLE
X11 (Cinnamon?): _NET_WM_SYNC_REQUEST stops working after releasing resize while still dragging mouse

### ISSUE THREAD

**Issue by dzaima** [HumbleUI/JWM#219]
Very cryptic problem, but it's annoying me to no end.

1. hold a corner of the window
2. drag around
3. while still dragging the mouse around, release left click (will not happen if you hold mouse, stop moving, and release while keeping the mouse pointer still)
4. observe that on future resizing its glitchy

Might be a Cinnamon/Linux Mint issue (would love to hear if this is reproducable on other systems), might be an issue with JWM's `_NET_WM_SYNC_REQUEST` usage/implementation.

edit: behavior in random other apps: GIMP & Krita have the same issue; Sublime Text, Nemo, and Gnome Terminal don't.

**Comment by tonsky** [comment]
Can you record a video? I couldn’t reproduce

**Comment by dzaima** [comment]
https://user-images.githubusercontent.com/5551338/157094990-3b372211-0096-4c23-8dfa-479bd078f71e.mp4

**Comment by dzaima** [comment]
(Gonna close this as this is definitely not JWMs fault)

**Comment by dzaima** [comment]
(fwiw, this is fixed on Linux Mint 21)

**Comment by tonsky** [comment]
Linux Mint sounds like a fun experience :)
