### ISSUE TITLE
AWT interoperability

### ISSUE THREAD

**Issue by bumfo** [HumbleUI/JWM#224]
Looks like 0.4.x works fine with AWT (tested on macOS OpenJDK 13), where 0.3.x is completely incompatible with AWT on macOS. Also notice that -XstartOnFirstThread seems to be no longer required on mac in 0.4.x. What's the changes behind that?

And should AWT interoperability be a feature of JWM and be guaranteed in future versions? This feature is quite important to me ;)

**Comment by dzaima** [comment]
[this](https://github.com/HumbleUI/JWM/issues/210) was the discussion about removing the need of `-XstartOnFirstThread`

**Comment by bumfo** [comment]
> @bumfo could you elaborate? What do you mean by AWT interoperability? JWM and AWT solve the same problem, how are you planning to use them together? And why?

I'm porting an AWT program to JWM, yet the previous version with -XstartOnFirstThread cannot co-exist with AWT at all. Since the AWT part is quite heavy, the ability to co-exist is very important for smooth transition. Also, some old API is declared with AWT classes, if they cannot co-exist, the program will fail.

**Comment by bumfo** [comment]
> Well, I’m glad new version works. Do you have any reason to stay on 0.3? Do you need anything fixed in 0.4?

I've switched to 0.4.x. Only to confirm future versions should continually works.
