### ISSUE TITLE
X11: Scroll not reported while some other mouse button is held down

### ISSUE THREAD

**Issue by dzaima** [HumbleUI/JWM#243]
So far I've traced it down to [this](https://github.com/HumbleUI/JWM/blob/8814b93ae484e469097530f99cd35bfdadd5f891/linux/cc/WindowManagerX11.cc#L334-L337):

While no mouse buttons are held, that gets two events, one with `deviceEvent->deviceid` being `2` and one with it being `10`; the `10` fails the `if` and thus doesn't get processed.

Whereas when some mouse button is held down, only the `10==deviceEvent->deviceid` event happens, and so nothing gets processed.

Hard-coding `deviceEvent->deviceid` there to always be `2` does give scroll updates, proving that receiving scroll updates while a button is held is possible, but of course such hard-coding won't work for an actual solution.

**Comment by jakeisnt** [comment]
Looks like this should be closed?

**Comment by dzaima** [comment]
yep
