### ISSUE TITLE
macOS: trackpad touch events

### ISSUE THREAD

**Issue by shaunlebron** [HumbleUI/JWM#249]
Looking at adding access to macOS trackpad touch events.  Some references to start:

* [Magic]: an example mac app that uses trackpad touch events for drawing
* [docs on macos touch events]( https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13-SW1)
* edit: [docs on web touch events](https://developer.mozilla.org/en-US/docs/Web/API/Touch_events)
* edit: [how SDL tracks touch events on macOS](https://github.com/libsdl-org/SDL/blob/a463aca0d1353be3fa45e09429b378cd28eb5a59/src/video/cocoa/SDL_cocoawindow.m#L1378-L1512)

[Magic]:https://apps.apple.com/us/app/magic-drawing-app/id1581223559?mt=12

**Comment by tonsky** [comment]
I think web api should be studied for this too

**Comment by shaunlebron** [comment]
The [Apple docs on touch events][doc] said to use `setAcceptsTouchEvents:YES`, but the compiler said it was deprecated for [allowedTouchTypes].  I had to find a [usage example] on GitHub.

The `acceptsTouchEvents` property also seemed necessary.  Does Apple have newer docs on this?

I confirmed that the touch events are being caught now (see 49a4483cda4619b45133482f95cee91e2620de32).  I will look next look at logging the touch event data to the window.

[usage example]:https://github.com/m1rr0r-t34m/SwipeTranslate/blob/ecf7e8190a79587f8a49dcb6906bbf86a7eed1d6/googleTranslateWidget/STDraggableView.m#L109-L115
[docs]:https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/HandlingTouchEvents/HandlingTouchEvents.html#//apple_ref/doc/uid/10000060i-CH13-SW1
[allowedTouchTypes]:https://developer.apple.com/documentation/appkit/nsview/2544839-allowedtouchtypes?language=objc

**Comment by shaunlebron** [comment]
I added `EventTrackpadTouch*` events and the dashboard event panel is logging them successfully.  I will look at drawing the touch points in a new trackpad panel.

**Comment by tonsky** [comment]
That would be cool!

**Comment by shaunlebron** [comment]
I put a trackpad panel next to the mouse panel:
https://user-images.githubusercontent.com/116838/205142978-943956e8-4b2b-4b01-ba1a-eb46aeac5f86.mp4

Problems so far:
1. The dashboard starts hiccuping when I move the touch points too quickly.  Not sure what’s going on there.
2. Touch point state goes out of sync if you use a four-finger gesture that exits the view (swipe up, down, out or in).  Not sure how to get external touch events to keep those in sync.
