### ISSUE TITLE
macOS: Pointer Lock API

### ISSUE THREAD

**Issue by shaunlebron** [HumbleUI/JWM#252]
This helps prevent accidentally exiting the view when tracking touch points in #249.

Web:
* [Pointer Lock API](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API)

Chromium:
* [setCursorLocked](https://github.com/chromium/chromium/blob/110.0.5464.1/content/app_shim_remote_cocoa/render_widget_host_view_cocoa.mm#L859-L869)

macOS:
* NSCursor [hide](https://developer.apple.com/documentation/appkit/nscursor/1527345-hide?language=objc) / [unhide](https://developer.apple.com/documentation/appkit/nscursor/1532996-unhide?language=objc)
* [CGAssociateMouseAndMouseCursorPosition](https://developer.apple.com/documentation/coregraphics/1454486-cgassociatemouseandmousecursorpo?language=objc) (freeze/thaw cursor)

**Comment by tonsky** [comment]
Will you make a PR?

**Comment by shaunlebron** [comment]
PR is up.  But I have to do some more digging to see how chromium adds the `movementX` and `movementY` properties to the mouse move event when pointer is locked.
