### ISSUE TITLE
"getScreens" and "getScreen" don't fully make sense for all platforms

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [HumbleUI/JWM#277]
I would like to know the reasoning behind `getScreens` and `getScreen`. I think that these aren't used and could be replaced where they are used (like adding `getScale` directly on a window). Also fairly sure that wayland doesn't even bother letting you list out all the screens, and X11 doesn't even really support it. In my opinion, it would make more sense to just get rid of screens altogether, and move the functions elsewhere. The only actually useful function in my opinion is `getScale`, and that can easily be moved to `Window`

This is a blocker for me on wayland, as there is no feasible way to implement it. It also is very jank on wayland, in a way that makes me think you weren't really meant to get the screen.

**Comment by tonsky** [comment]
Screen configuration is pretty important to position window correctly, e.g. in the center of the screen. Also to make sure we are not creating window bigger than screen.

I agree with @dzaima, it’s unfortunate that Wayland doesn’t support it, but all the other platforms do and it’s pretty useful there. Maybe make Wayland version always return 1024x768 screen or something?

**Comment by TheDrawingCoder-Gamer** [comment]
Returning just the size of the window makes sense then. I'm ok with that.
