### ISSUE TITLE
macOS: Created new windows missing decorations.

### ISSUE THREAD

**Issue by FledgeXu** [HumbleUI/JWM#290]
System: `Apple M2 Max 14.4 (23E214)`
JVM: 
```
java version "21.0.2" 2024-01-16 LTS
Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30, mixed mode, sharing)
```
Reproduce Steps:
1. `python3 script/run.py` to start dashboard example.
2. press CMD+N to create a new window.

Bugs:
<img width="1746" alt="image" src="https://github.com/HumbleUI/JWM/assets/16664654/a9603983-b517-4ca3-ac02-cc3f7f55bf50">

I'm not sure it's by design or not…

**Comment by tonsky** [comment]
Yes, this is just how demo app is set up. Each new window has new decoration style. Not a bug
