### ISSUE TITLE
Plain system events

### ISSUE THREAD

**Issue by kqvanity** [HumbleUI/JWM#292]
Hello,

I was wondering If I can use this library to detect system events across-various platforms e.g., mouse click, mouse release, text highlighted, certain other window clicked, text highlighted & cords, etc.
The detection in question is the one without relying on any opened library windows/within its frame. On the OS itself.

**Comment by tonsky** [comment]
No, I don’t think so. It mostly tracks events on the window it created itself. Also text selected is not an event

**Comment by kqvanity** [comment]
Oh. okay!
